```{r}
library(tidyverse)
library(janitor)
library(slugify)
```

```{r}
boe_spending <- read_csv("~/code/boe_spending/County_Board_of_Education_-_Spending_Disclosures.csv") %>% clean_names() 
```

### Baltimore County 2021 & 2022

need to load, group by and summarize as these appear to be individual payments?

```{r}
baltimore_county_2021 <- read_csv("~/code/boe_spending/baltimore_county_2021.csv") %>% clean_names()

baltimore_county_2021_totals <- baltimore_county_2021 %>% 
  group_by(fiscal_year, agency_name, payee_name, payee_zip, purpose_of_payment_baltimore_county) %>% 
  summarize(total = sum(amount)) %>% 
  filter(total >= 25000) %>% 
  rename(purpose_of_payment_baltimore_county_only = purpose_of_payment_baltimore_county, amount = total)

baltimore_county_2022 <- read_csv("~/code/boe_spending/baltimore_county_2022.csv") %>% clean_names()

baltimore_county_2022_totals <- baltimore_county_2022 %>% 
  group_by(fiscal_year, agency_name, payee_name, payee_zip, purpose_of_payment_baltimore_county_only) %>% 
  summarize(total = sum(amount)) %>% 
  filter(total >= 25000) %>% 
  rename(amount = total)

boe_spending <- bind_rows(boe_spending, baltimore_county_2021_totals, baltimore_county_2022_totals)

```
### Baltimore City 2021 Add

```{r}
baltimore_city_2021 <- read_csv("baltimore_city_2021.csv") %>% clean_names() %>% group_by(vendor) %>% summarize(amount = sum(amount)) %>% 
  mutate(fiscal_year = 2021, agency_name = 'Baltimore City Public Schools') %>% 
  rename(payee_name = vendor)

boe_spending <- bind_rows(boe_spending, baltimore_city_2021)

```



### Anne Arundel Replacement

```{r}
anne_arundel_original <- boe_spending %>% filter(agency_name == 'Anne Arundel Co. Public Schools', fiscal_year > 2019)

anne_arundel_replacement <- read_csv("anne_arundel_replacement.csv") %>% mutate(agency_name = str_to_upper(agency_name), payee_name_clean = str_to_upper(payee_name))

anne_arundel_replacement <- anne_arundel_replacement %>% left_join(anne_arundel_original, by=c('payee_name', 'fiscal_year')) %>% select(-agency_name.y, -amount.y) %>% rename(agency_name = agency_name.x, amount = amount.x)

boe_spending <- boe_spending %>% anti_join(anne_arundel_original)

boe_spending <- bind_rows(boe_spending, anne_arundel_replacement) %>% mutate(agency_name = str_to_upper(agency_name), payee_name_clean = str_to_upper(payee_name), payee_zip5 = str_sub(payee_zip, 1, 5))

```

### Montgomery 2019 Replacement

```{r}
montgomery_original <- boe_spending %>% filter(agency_name == 'MONTGOMERY COUNTY PUBLIC SCHOOL', fiscal_year == 2019)

montgomery_replacement <- read_csv("montgomery_2019.csv") %>% clean_names() %>% mutate(agency_name = str_to_upper(agency_name), payee_name_clean = str_to_upper(payee_name))

#montgomery_replacement <- montgomery_replacement %>% left_join(montgomery_original, by=c('payee_name', 'fiscal_year')) %>% select(-agency_name.y, -amount.y) %>% rename(agency_name = agency_name.x, amount = amount.x, payee_zip = payee_zip.x, payee_name_clean = payee_name_clean.x)

boe_spending <- boe_spending %>% anti_join(montgomery_original)

boe_spending <- bind_rows(boe_spending, montgomery_replacement) %>% mutate(agency_name = str_to_upper(agency_name), payee_name_clean = str_to_upper(payee_name), payee_zip5 = str_sub(payee_zip, 1, 5))
```


### General cleaning

```{r}
boe_spending <- boe_spending %>% 
  mutate(payee_name_clean = str_squish(payee_name_clean)) %>% 
  mutate(payee_name_clean = str_replace(payee_name_clean, ",", "")) %>%
  mutate(payee_name_clean = str_replace(payee_name_clean, "[.]", "")) %>%
  mutate(payee_name_clean = str_replace(payee_name_clean, "INC.", "INC")) %>%
  mutate(payee_name_clean = str_replace(payee_name_clean, "(EFT)", "")) %>% 
  mutate(payee_name_clean = str_replace(payee_name_clean, "(EFT ONLY)", "")) %>% 
  mutate(agency_name = str_replace(agency_name, "ST.", "ST")) %>% 
  mutate(agency_name = str_squish(agency_name))

boe_spending <- boe_spending %>% 
  mutate(agency_name = case_when(
    agency_name == 'ANNE ARUNDEL CO. PUBLIC SCHOOLS' ~ 'ANNE ARUNDEL COUNTY PUBLIC SCHOOLS',
    agency_name == 'BALTIMORE CITY SCHOOLS' ~ 'BALTIMORE CITY PUBLIC SCHOOLS',
    agency_name == 'BALITMORE CITY PUBLIC SCHOOLS' ~ 'BALTIMORE CITY PUBLIC SCHOOLS',
    agency_name == 'CAROLINE COUNTY BOARD OF EDUCATION' ~ 'CAROLINE COUNTY PUBLIC SCHOOLS',
    agency_name == 'DORCHESTR COUNTY BOARD OF EDUCATION' ~ 'DORCHESTER COUNTY PUBLIC SCHOOLS',
    agency_name == 'DORCHESTR COUNTY PUBLIC SCHOOLS' ~ 'DORCHESTER COUNTY PUBLIC SCHOOLS',
    agency_name == 'MONTGOMERY COUNTY PUBLIC SCHOOL' ~ 'MONTGOMERY COUNTY PUBLIC SCHOOLS',
    agency_name == "PRINCE GEORGES' COUNTY PUBLIC SCHOOLS" ~ "PRINCE GEORGE'S COUNTY PUBLIC SCHOOLS",
    agency_name == 'WORCESTR COUNTY BOARD OF ED' ~ 'WORCESTER COUNTY PUBLIC SCHOOLS',
    TRUE ~ agency_name
  ))

boe_spending <- boe_spending %>% 
  drop_na(agency_name)
```



### Years for Agencies

```{r}
boe_spending %>% group_by(agency_name, fiscal_year) %>% summarize(count = n()) %>% pivot_wider(names_from = fiscal_year, values_from = count) 
```


### County-specific cleaning
```{r}
# Howard
boe_spending <- boe_spending %>% 
  mutate(payee_name_clean = str_replace(payee_name_clean, '(EFT)','')) %>% mutate(payee_name_clean = str_replace(payee_name_clean, ' (EFTPS ONLY)',''))

```


### OpenRefine results

```{r}

boe_final <- read_csv("boe_final.csv")

boe_spending <- boe_spending %>% 
  mutate(slug = case_when(
    agency_name == 'ALLEGANY COUNTY PUBLIC SCHOOLS' ~ 'allegany-county',
    agency_name == 'ANNE ARUNDEL COUNTY PUBLIC SCHOOLS' ~ 'anne-arundel-county',
    agency_name == 'BALTIMORE CITY PUBLIC SCHOOLS' ~ 'baltimore-city',
    agency_name == 'BALTIMORE COUNTY PUBLIC SCHOOLS' ~ 'baltimore-county',
    agency_name == 'CALVERT COUNTY PUBLIC SCHOOLS' ~ 'calvert-county',
    agency_name == 'CARROLL COUNTY PUBLIC SCHOOLS' ~ 'carroll-county',
    agency_name == 'CAROLINE COUNTY PUBLIC SCHOOLS' ~ 'caroline-county',
    agency_name == 'CECIL COUNTY PUBLIC SCHOOLS' ~ 'cecil-county',
    agency_name == 'CHARLES COUNTY PUBLIC SCHOOLS' ~ 'charles-county',
    agency_name == 'DORCHESTER COUNTY PUBLIC SCHOOLS' ~ 'dorchester-county',
    agency_name == 'FREDERICK COUNTY PUBLIC SCHOOLS' ~ 'frederick-county',
    agency_name == 'HARFORD COUNTY PUBLIC SCHOOLS' ~ 'harford-county',
    agency_name == 'OAKLAND, GARRETT COUNTY PUBLIC SCHOOLS' ~ 'garrett-county',
    agency_name == 'HOWARD COUNTY PUBLIC SCHOOLS' ~ 'howard-county',
    agency_name == 'KENT COUNTY PUBLIC SCHOOLS' ~ 'kent-county',
    agency_name == 'MONTGOMERY COUNTY PUBLIC SCHOOLS' ~ 'montgomery-county',
    agency_name == "PRINCE GEORGE'S COUNTY PUBLIC SCHOOLS" ~ 'prince-georges-county',
    agency_name == "ST MARY'S COUNTY PUBLIC SCHOOLS" ~ 'st-marys-county',
    agency_name == 'WORCESTER COUNTY PUBLIC SCHOOLS' ~ 'worcester-county',
    agency_name == "QUEEN ANNE'S COUNTY PUBLIC SCHOOLS" ~ 'queen-annes-county',
    agency_name == 'SOMERSET COUNTY PUBLIC SCHOOLS' ~ 'somerset-county',
    agency_name == 'TALBOT COUNTY PUBLIC SCHOOLS' ~ 'talbot-county',
    agency_name == 'WASHINGTON COUNTY PUBLIC SCHOOLS' ~ 'washington-county',
    agency_name == 'WICOMICO COUNTY PUBLIC SCHOOLS' ~ 'wicomico-county'
  ))

boe_final <- boe_final %>% 
  mutate(payee_name_refined = str_replace_all(payee_name_refined, "\u00A0", " "))

boe_payees_final <- boe_final %>% 
  distinct(payee_name_clean, payee_name_refined) 
  
boe_spending_cleaned <- boe_spending %>% 
  left_join(boe_payees_final)

boe_spending_cleaned <- boe_spending_cleaned %>% 
  mutate(payee_name_refined = case_when(
    is.na(payee_name_refined) ~ payee_name_clean,
    TRUE ~ payee_name_refined
  ))

boe_spending_cleaned <- boe_spending_cleaned %>% select(agency_name, fiscal_year, amount, payee_name_refined, payee_zip5, purpose_of_payment_baltimore_county_only, slug) %>% 
  rename(payee_name = payee_name_refined, payee_zip = payee_zip5) %>%
  group_by(agency_name, fiscal_year, payee_name, payee_zip, purpose_of_payment_baltimore_county_only, slug) %>% 
  summarize(total = sum(amount)) %>% 
  rename(amount = total)

write_csv(boe_spending_cleaned, "boe_spending_cleaned.csv")
```


